name: Continous Integration
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm test
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v4
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.HTTP_PLAYGROUND_DEV_EC2_SSH_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: Rsync to remote host
        run: |
          rsync -e "ssh -i ~/.ssh/private.key" -ravz ./${REPOSITORY_NAME} ${EC2_USER}@${EC2_PUBLIC_IP}:/${REPOSITORY_NAME}
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          EC2_USER: ubuntu
          EC2_PUBLIC_IP: 13.53.87.144
